### ISSUE TITLE
🐛 [Bug] Model compiles in Docker image, but not locally

### ISSUE THREAD

**Issue by lennartmoritz** [NVIDIA/Torch-TensorRT#1048]
##  Bug Description

My code is working within the Nvidia Docker base image but on my local installation.
I supply a copy of a traced model to my code. For the Docker image with Torch-TensorRT 1.1.0a0, which is based on pytorch 1.12, I traced the model with the same pytorch version. For released local version of Torch-TensorRT is 1.0.0, which is based on pytorch 1.10, I traced the model with the same pytorch version and also with pytorch 1.12, since I now have files for both. Is this an Issue I have to fix in my local code or should I wait for a 1.1 local release?

Well, after writing this I just saw there is a new Version 1.1. released for local Torch-TensorRT. I will update my local version and check if this fixes the issue. If it does I'll close the issue and if not I'll update it.
### My code:
```
class ReidExtractor:
    def __init__(self,config, logger, lock):
        '''
        Set up the Reid feature extractor
        '''
        self.lock = lock
        self.logger = logger

        self.batch_size = 16

        trt_ts_model_file = osp.splitext(self.mc_cfg.model_file)[0] + ".ts"
        if osp.exists(trt_ts_model_file):
            # load previously compiled trt model from file
            pass # code removed
        else:
            # load a torchscript model & compile it into a trt model
            with self.lock:
                self.logger.info(f"Compiling new torch-tensorrt model!")
            self.model = torch.jit.load(self.mc_cfg.model_file)
            self.model.cuda()
            self.model.eval()
            inputs = [torch_tensorrt.Input(
                shape=[self.batch_size, 3, self.mc_cfg.height, self.mc_cfg.width],
                dtype=torch.float
            )]
            enabled_precisions = {torch.float}
            # CRASH HAPPENS IN NEXT LINE
            self.model = torch_tensorrt.compile(self.model, inputs=inputs, enabled_precisions=enabled_precisions, truncate_long_and_double=True)
            # store the compiled model
            torch.jit.save(self.model, trt_ts_model_file)
```
### Logs in Debug mode
<details>
  <summary>Click to expand!</summary>
  
```
DEBUG: [Torch-TensorRT] - GlobalPoolingConverter: Output tensor shape: [32, 512, 1, 1]
DEBUG: [Torch-TensorRT TorchScript Conversion Context] - Evaluating %2409 : int = aten::size(%v.1, %1929) # /home/lennux/Repositories/deep-person-reid/torchreid/models/osnet_ain.py:437:0
WARNING: [Torch-TensorRT] - There may be undefined behavior using dynamic shape and aten::size
DEBUG: [Torch-TensorRT TorchScript Conversion Context] - Found the value to be: 32
DEBUG: [Torch-TensorRT TorchScript Conversion Context] - Evaluating %2410 : int[] = prim::ListConstruct(%2409, %1930)
DEBUG: [Torch-TensorRT TorchScript Conversion Context] - Found the value to be: [32, -1]
INFO: [Torch-TensorRT TorchScript Conversion Context] - Adding Layer %input.24 : Tensor = aten::view(%v.1, %2410) # /home/lennux/Repositories/deep-person-reid/torchreid/models/osnet_ain.py:437:0 (ctx.AddLayer)
DEBUG: [Torch-TensorRT TorchScript Conversion Context] - Node input is an already converted tensor
DEBUG: [Torch-TensorRT TorchScript Conversion Context] - Node input is a result of a previously evaluated value
DEBUG: [Torch-TensorRT] - ITensor shape: [32, 512, 1, 1]
DEBUG: [Torch-TensorRT] - ITensor type: Float32
DEBUG: [Torch-TensorRT] - Output tensor shape: [32, 512]
DEBUG: [Torch-TensorRT TorchScript Conversion Context] - Evaluating %2414 : int = prim::Constant[value=1]()
DEBUG: [Torch-TensorRT TorchScript Conversion Context] - Found the value to be: 1
INFO: [Torch-TensorRT TorchScript Conversion Context] - Adding Layer %2415 : Tensor = aten::t(%self.fc.0.weight) (ctx.AddLayer)
DEBUG: [Torch-TensorRT TorchScript Conversion Context] - Node input is a result of a previously evaluated value
DEBUG: [Torch-TensorRT TorchScript Conversion Context] - Found IValue containing object of type Float(512, 512, strides=[512, 1], requires_grad=0, device=cuda:0)
DEBUG: [Torch-TensorRT] - Weights: [512, 512]
    Data Type: Float32
    Number of input maps: 512
    Number of output maps: 512
    Element shape: [1]
DEBUG: [Torch-TensorRT TorchScript Conversion Context] - Freezing tensor 0x563881504358 as an IConstantLayer
DEBUG: [Torch-TensorRT] - ITensor shape: [512, 512]
DEBUG: [Torch-TensorRT] - ITensor type: Float32
DEBUG: [Torch-TensorRT] - Output tensor shape: [512, 512]
INFO: [Torch-TensorRT TorchScript Conversion Context] - Adding Layer %2416 : Tensor = aten::matmul(%input.24, %2415) (ctx.AddLayer)
DEBUG: [Torch-TensorRT TorchScript Conversion Context] - Node input is an already converted tensor
DEBUG: [Torch-TensorRT TorchScript Conversion Context] - Node input is an already converted tensor
DEBUG: [Torch-TensorRT] - ITensor shape: [32, 512]
DEBUG: [Torch-TensorRT] - ITensor type: Float32
DEBUG: [Torch-TensorRT] - ITensor shape: [512, 512]
DEBUG: [Torch-TensorRT] - ITensor type: Float32
DEBUG: [Torch-TensorRT] - Output tensor shape: [32, 512]
INFO: [Torch-TensorRT TorchScript Conversion Context] - Adding Layer %2417 : Tensor = trt::const(%self.fc.0.bias) (ctx.AddLayer)
DEBUG: [Torch-TensorRT TorchScript Conversion Context] - Node input is a result of a previously evaluated value
DEBUG: [Torch-TensorRT] - Weights: [512]
    Data Type: Float32
    Number of input maps: 512
    Number of output maps: 512
    Element shape: [1]
DEBUG: [Torch-TensorRT TorchScript Conversion Context] - Freezing tensor %2417 : Tensor = trt::const(%self.fc.0.bias) as an IConstantLayer
DEBUG: [Torch-TensorRT] - Output tensor shape: [512]
INFO: [Torch-TensorRT TorchScript Conversion Context] - Adding Layer %2418 : Tensor = aten::add(%2417, %2416, %2414) (ctx.AddLayer)
DEBUG: [Torch-TensorRT TorchScript Conversion Context] - Node input is an already converted tensor
DEBUG: [Torch-TensorRT TorchScript Conversion Context] - Node input is an already converted tensor
DEBUG: [Torch-TensorRT TorchScript Conversion Context] - Node input is a result of a previously evaluated value
DEBUG: [Torch-TensorRT] - ITensor shape: [512]
DEBUG: [Torch-TensorRT] - ITensor type: Float32
DEBUG: [Torch-TensorRT] - ITensor shape: [32, 512]
DEBUG: [Torch-TensorRT] - ITensor type: Float32
DEBUG: [Torch-TensorRT] - Output tensor shape: [32, 512]
INFO: [Torch-TensorRT TorchScript Conversion Context] - Adding Layer %input.1 : Tensor = aten::batch_norm(%2418, %self.fc.1.weight, %self.fc.1.bias, %self.fc.1.running_mean, %self.fc.1.running_var, %1452, %1458, %1459, %1455) # /home/lennux/anaconda3/envs/torchreid/lib/python3.7/site-packages/torch/nn/functional.py:2387:0 (ctx.AddLayer)
DEBUG: [Torch-TensorRT TorchScript Conversion Context] - Node input is an already converted tensor
DEBUG: [Torch-TensorRT TorchScript Conversion Context] - Node input is a result of a previously evaluated value
DEBUG: [Torch-TensorRT TorchScript Conversion Context] - Node input is a result of a previously evaluated value
DEBUG: [Torch-TensorRT TorchScript Conversion Context] - Node input is a result of a previously evaluated value
DEBUG: [Torch-TensorRT TorchScript Conversion Context] - Node input is a result of a previously evaluated value
DEBUG: [Torch-TensorRT TorchScript Conversion Context] - Node input is a result of a previously evaluated value
DEBUG: [Torch-TensorRT TorchScript Conversion Context] - Node input is a result of a previously evaluated value
DEBUG: [Torch-TensorRT TorchScript Conversion Context] - Node input is a result of a previously evaluated value
DEBUG: [Torch-TensorRT TorchScript Conversion Context] - Node input is a result of a previously evaluated value
DEBUG: [Torch-TensorRT] - momentum disregarded
DEBUG: [Torch-TensorRT] - training disregarded
DEBUG: [Torch-TensorRT] - cudnn disregarded
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lennux/anaconda3/envs/omct/lib/python3.7/site-packages/torch_tensorrt/_compile.py", line 97, in compile
    return torch_tensorrt.ts.compile(ts_mod, inputs=inputs, enabled_precisions=enabled_precisions, **kwargs)
  File "/home/lennux/anaconda3/envs/omct/lib/python3.7/site-packages/torch_tensorrt/ts/_compiler.py", line 119, in compile
    compiled_cpp_mod = _C.compile_graph(module._c, _parse_compile_spec(spec))
RuntimeError: [Error thrown at core/conversion/converters/impl/batch_norm.cpp:74] Expected orig_shape.nbDims > 2 to be true but got false
Unable to create batch normalization layer from node: %input.1 : Tensor = aten::batch_norm(%2418, %self.fc.1.weight, %self.fc.1.bias, %self.fc.1.running_mean, %self.fc.1.running_var, %1452, %1458, %1459, %1455) # /home/lennux/anaconda3/envs/torchreid/lib/python3.7/site-packages/torch/nn/functional.py:2387:0
```
</details>

## Expected behavior

My code should run locally as well as within the Docker container.

## Environment

 - Torch-TensorRT Version (e.g. 1.0.0):  1.0.0
 - PyTorch Version (e.g. 1.0): 1.10.0
 - CPU Architecture: x86_64
 - OS (e.g., Linux): x86_64
 - How you installed PyTorch (`conda`, `pip`, `libtorch`, source): `conda install pytorch torchvision cudatoolkit=11.3 -c pytorch`
 - Build command you used (if compiling from source):  -
 - Are you using local sources or building from archives: -
 - Python version: 3.7.7
 - CUDA version: Came with pytorch, so (11.3)
 - GPU models and configuration: RTX 2060

**Comment by lennartmoritz** [comment]
Thank you, my issue was fixed with 1.1.
