### ISSUE TITLE
🐛 [Bug]  Zero-point must be Int32, Float or Half, found Long

### ISSUE THREAD

**Issue by XuanBaby** [NVIDIA/Torch-TensorRT#713]
##  Bug Description

when export QAT model  to torchscript module , get error 

## To Reproduce

1. form examples : https://github.com/NVIDIA/Torch-TensorRT/tree/master/examples/int8/training/vgg16
2. run python3 export_qat.py vgg16_ckpts/ckpt_epoch110.pth

## Environment

> Build information about Torch-TensorRT can be found by turning on debug messages

 - Torch-TensorRT Version (e.g. 1.0.0):
 - PyTorch Version (e.g. 1.10.0+cu113.):
 - CPU Architecture: x86
 - OS (e.g., Linux): Ubuntu 20.04.3 LTS
 - How you installed PyTorch (`conda`, `pip`, `libtorch`, source): conda 
 - Build command you used (if compiling from source): bazel & python3 setup.py bdist_wheel
 - Are you using local sources or building from archives: using local sources
 - Python version: 3.8
 - CUDA version: 11.3
 - GPU models and configuration: A100
 - Any other relevant information:

## Additional context
`python3 export_qat.py vgg16_ckpts/ckpt_epoch110.pth`
`E1112 04:58:06.402409 140272063088448 tensor_quantizer.py:120] Fake quantize mode doesn't use scale explicitly!
W1112 04:58:06.408374 140272063088448 tensor_quantizer.py:280] Use Pytorch's native experimental fake quantization.
/opt/conda/lib/python3.8/site-packages/pytorch_quantization/nn/modules/tensor_quantizer.py:285: TracerWarning: Converting a tensor to a Python number might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  inputs, amax.item() / bound, 0,
/opt/conda/lib/python3.8/site-packages/pytorch_quantization/nn/modules/tensor_quantizer.py:291: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  quant_dim = list(amax.shape).index(list(amax_sequeeze.shape)[0])
Traceback (most recent call last):
  File "export_qat.py", line 79, in <module>
    jit_model = torch.jit.trace(model, images.to("cuda"))
  File "/opt/conda/lib/python3.8/site-packages/torch/jit/_trace.py", line 741, in trace
    return trace_module(
  File "/opt/conda/lib/python3.8/site-packages/torch/jit/_trace.py", line 958, in trace_module
    module._c._create_method_from_trace(
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1090, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/work/Joanna/Torch_TensorRT/Torch-TensorRT-1.0.0/examples/int8/training/vgg16/vgg16.py", line 47, in forward
    x = self.features(x)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1090, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/container.py", line 141, in forward
    input = module(input)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1090, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_quantization/nn/modules/quant_conv.py", line 119, in forward
    quant_input, quant_weight = self._quant(input)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_quantization/nn/modules/quant_conv.py", line 85, in _quant
    quant_weight = self._weight_quantizer(self.weight)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1090, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_quantization/nn/modules/tensor_quantizer.py", line 345, in forward
    outputs = self._quant_forward(inputs)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_quantization/nn/modules/tensor_quantizer.py", line 313, in _quant_forward
    outputs = self._fb_fake_quant(inputs, amax)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_quantization/nn/modules/tensor_quantizer.py", line 293, in _fb_fake_quant
    outputs = torch.fake_quantize_per_channel_affine(
RuntimeError: Zero-point must be Int32, Float or Half, found Long`

**Comment by narendasan** [comment]
@peri044 can you link the patch for the toolkit?

**Comment by peri044** [comment]
Hello @XuanBaby Please apply this patch to your pytorch_quantization toolkit https://github.com/NVIDIA/TensorRT/pull/1606
This patch will soon be released upstream.

**Comment by XuanBaby** [comment]
@peri044 Bug is solved , Thank you very much !

**Comment by ziyouzizai111** [comment]
您好，我想问下这个bug怎样解决的呢？请大神指点下。谢谢 @XuanBaby

**Comment by XuanBaby** [comment]
@ziyouzizai111  修改文件：[tools/pytorch-quantization/pytorch_quantization/nn/modules/tensor_quantizer.py] 
![image](https://user-images.githubusercontent.com/29744738/161361870-b7739fbb-f497-4d04-97d1-96b65a1d8edc.png)

**Comment by ziyouzizai111** [comment]
> @ziyouzizai111 修改文件：[tools/pytorch-quantization/pytorch_quantization/nn/modules/tensor_quantizer.py] ![image](https://user-images.githubusercontent.com/29744738/161361870-b7739fbb-f497-4d04-97d1-96b65a1d8edc.png)

谢谢您，我这边改了，权重能保存了，但也出现了很多[E0402的错误:tensor_quantizer.py:120]Fake quantize mode doesn't use scale explicitly!!!  我非常好奇：为啥是error错误也能运行呢？搞不懂，但是非常感谢您的解答！
