### ISSUE TITLE
🐛 [Bug] Encountered a bug of multiprocessing inference when using Torch-TensorRT

### ISSUE THREAD

**Issue by rajusm** [NVIDIA/Torch-TensorRT#758]
##  Bug Description

Hi @narendasan ,
Thank you for this nice project. Currently I built latest `torch_tensorrt` from the latest release version `1.0.0` for Ampere A10 GPU with CUDA 11.4, Nvidia Driver 470.86, CUDNN 8.2.4, TensorRT 8.2.1, torch 1.10.0a0+git36449ea (CUDA supported), torchvision 0.11.0a0+fa347eb, yolov5m model. I am able to run single python process without any error. However, I can not run multiple python process and I am using `pebble` ProcessPool similar to multiprocessing. When I run multiprocessing of the same inference pipeline I get below error:
```
RuntimeError: [Error thrown at core/runtime/runtime.cpp:74] Expected (cudaSetDevice(cuda_device.id) == cudaSuccess) to be true but got false
Unable to set device: Device(ID: 0, Name: NVIDIA A10, SM Capability: 8.6, Type: GPU)as active device
```
## To Reproduce

1. Compile model.
1. Please use any multiprocessing library like pebble, multiprocessing.
1. Run multiprocessing python script to load the model. 

Sample single process working code:
```
import multiprocessing
import time
import torch
import torch_tensorrt

device_gpu = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

def sleepy_man():
    model_path = "INSERT_MODEL_PATH"
    # Model loading
    t_0 = time.time()
    model = torch.jit.load(model_path)
    model = model.to(device_gpu)
    print(".ts model loading time : ",time.time()- t_0)

tic = time.time()
sleepy_man()
# p1 =  multiprocessing.Process(target= sleepy_man)
# p2 =  multiprocessing.Process(target= sleepy_man)
# p1.start()
# p2.start()
# p1.join()
# p2.join()
toc = time.time()

print('Done in {:.4f} seconds'.format(toc-tic))
```
**output:**
```
.ts model loading time :  2.7014000415802
Done in 2.7141 seconds
```
Sample multiprocessing not working code:
```
import multiprocessing
import time
import torch
import torch_tensorrt

device_gpu = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

def sleepy_man():
    model_path = "INSERT_MODEL_PATH"
    # Model loading
    t_0 = time.time()
    model = torch.jit.load(model_path)
    model = model.to(device_gpu)
    print(".ts model loading time : ",time.time()- t_0)

tic = time.time()
# sleepy_man()
p1 =  multiprocessing.Process(target= sleepy_man)
p2 =  multiprocessing.Process(target= sleepy_man)
p1.start()
p2.start()
p1.join()
p2.join()
toc = time.time()

print('Done in {:.4f} seconds'.format(toc-tic))
```
**Output:**
```
.ts model loading time :  2.649552345275879
Process Process-1:
Traceback (most recent call last):
  File "/home/user/anaconda3/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/user/anaconda3/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "test.py", line 12, in sleepy_man
    model = torch.jit.load(model_path)
  File "/home/user/anaconda3/lib/python3.7/site-packages/torch/jit/_serialization.py", line 161, in load
    cpp_module = torch._C.import_ir_module(cu, str(f), map_location, _extra_files)
RuntimeError: [Error thrown at core/runtime/runtime.cpp:74] Expected (cudaSetDevice(cuda_device.id) == cudaSuccess) to be true but got false
Unable to set device: Device(ID: 0, Name: NVIDIA A10, SM Capability: 8.6, Type: GPU)as active device

Process Process-2:
Traceback (most recent call last):
  File "/home/user/anaconda3/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/user/anaconda3/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "test.py", line 12, in sleepy_man
    model = torch.jit.load(model_path)
  File "/home/user/anaconda3/lib/python3.7/site-packages/torch/jit/_serialization.py", line 161, in load
    cpp_module = torch._C.import_ir_module(cu, str(f), map_location, _extra_files)
RuntimeError: [Error thrown at core/runtime/runtime.cpp:74] Expected (cudaSetDevice(cuda_device.id) == cudaSuccess) to be true but got false
Unable to set device: Device(ID: 0, Name: NVIDIA A10, SM Capability: 8.6, Type: GPU)as active device

Done in 2.8852 seconds

```
## Environment

> Build information about Torch-TensorRT can be found by turning on debug messages

 - Torch-TensorRT Version (e.g. 1.0.0): 1.0.0 (custom build-1.0.0+55c3bab4)
 - PyTorch Version (e.g. 1.0): 1.10.0 (custom build-1.10.0a0+git36449ea)
 - CPU Architecture: x86_64
 - OS (e.g., Linux): Linux
 - How you installed PyTorch (`conda`, `pip`, `libtorch`, source): Build from source using conda
 - Build command you used (if compiling from source): ref: https://github.com/pytorch/pytorch#from-source
 - Are you using local sources or building from archives: local
 - Python version: 3.7.6
 - CUDA version: 11.4
 - GPU models and configuration: Ampere A10  24GB
 - Any other relevant information: sm_86

## Additional context

`nvidia-smi`
![image](https://user-images.githubusercontent.com/57783623/144395419-b53ea7ab-1924-438e-88bb-30c76a827a06.png)

`nvcc`
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Mon_Oct_11_21:27:02_PDT_2021
Cuda compilation tools, release 11.4, V11.4.152
Build cuda_11.4.r11.4/compiler.30521435_0
```

**Comment by narendasan** [comment]
If you run the model in PyTorch alone does this workflow work properly. There might be some issue with how multiprocessing and cuda device apis work but that would be the first thing to check

**Comment by rajusm** [comment]
@narendasan yes, if I run single python process, the model works smoothly as expected. When I changed it to multiprocessing to run more than 1 process it stopped and throws above mentioned error.

I also provided a sample script to reproduce the error with multiprocessing.

**Comment by narendasan** [comment]
What I meant is if you run the model without compiling with torch-tensorrt does the multiprocessing version work?

**Comment by rajusm** [comment]
Hi @narendasan yes it works. I tested the Yolov5 Pytorch model with multiprocessing. Below attached my tested results:

Pytorch model with multiprocessing:
```
import multiprocessing
import time
import torch
#import torch_tensorrt

device_gpu = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

def sleepy_man():
    model_path = "YOUR_YOLOV5_PYTORCH_MODEL.pt"
    # Model loading
    t_0 = time.time()
    model = torch.load(model_path)
    #model = model.to(device_gpu)
    print(".pt model loading time : ",time.time()- t_0)

tic = time.time()
#sleepy_man()
p1 =  multiprocessing.Process(target= sleepy_man)
p2 =  multiprocessing.Process(target= sleepy_man)
p1.start()
p2.start()
p1.join()
p2.join()
toc = time.time()

print('Done in {:.4f} seconds'.format(toc-tic))
```
Output:
```
.pt model loading time :  0.6762559413909912
.pt model loading time :  0.7210562229156494
Done in 0.7439 seconds
```
Sample model file: https://github.com/ultralytics/yolov5/releases/download/v4.0/yolov5m.pt

**Comment by rajusm** [comment]
@narendasan I tested the yolov5m pytorch model without compiling and its working with multiprocessing. Below are my test script and output:
Kindly skip `time.sleep(10)`, I had to use it to take screenshot.
```
import sys
import multiprocessing as mp
import torch
import time

sys.path.insert(0, './yolov5')

device_gpu = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

def sleepy_man():
    model_path = "yolov5/yolov5m.pt"
    # Model loading
    t_0 = time.time()
    model = torch.load(model_path)
    model = model["model"].to(device_gpu)
    print(".pt model loading time : ",time.time()- t_0)
    time.sleep(10)

if __name__ == '__main__':
    mp.set_start_method('spawn')
    tic = time.time()
    p1 = mp.Process(target=sleepy_man)
    p2 = mp.Process(target=sleepy_man)
    p1.start()
    p2.start()
    p1.join()
    p2.join()
    toc = time.time()
    print('Done in {:.4f} seconds'.format(toc-tic))
```
Output:
```
.pt model loading time :  2.3629162311553955
.pt model loading time :  2.353997230529785
Done in 13.7802 seconds
```

Multi-process 
![Screenshot from 2021-12-06 17-33-23](https://user-images.githubusercontent.com/57783623/144823493-e1c534f6-ccc5-4cec-80b8-0493df74bbb8.png)

**Comment by rajusm** [comment]
Hi @narendasan 

Is there any update on this multiprocessing inference?

**Comment by peduajo** [comment]
Is there any solution about this? I'm having a similar error in C++ using libtorch + torch_tensorrt. Everything works fine using a single process, but with multiprocessing it crashes with the following line when trying to load the model with `torch::jit::load()`:

```
terminate called after throwing an instance of 'torch_tensorrt::Error'.
  what(): [Error thrown at /home/eduardo/Documents/project/TensorRT/core/runtime/runtime.cpp:99] Expected (cudaGetDevice(reinterpret_cast<int*>(&device)) == cudaSuccess) to be true but got false
Unable to get current device (runtime.get_current_device)
```

My multiprocessing pipeline was working fine without tensorRT, using TorchScript directly. For more information I show how I do the multiprocessing:

```
      pid_t pids[args.num_multiprocessing];

      for (int i = 0; i < args.num_multiprocessing; ++i) {
          pids[i] = fork();
          if (pids[i] < 0) {
          } else if (pids[i] == 0) {
              this->_generate_self_play_data(model_path, iteration, i);
              _exit(0);
          }
      }

      for (int i = 0; i < args.num_multiprocessing; ++i) {
          int status;
          waitpid(pids[i], &status, 0); 
          if (WIFEXITED(status)) {
              std::cout << "Child process " << i + 1 << " with PID: " << pids[i] << "ended with state: " << WEXITSTATUS(status) << std::endl;
              if (WEXITSTATUS(status) == 1) {
                  exit(EXIT_FAILURE);
              }
          }else{
              if (WIFSIGNALED(status)) {
                  int signal_number = WTERMSIG(status);
                  std::cerr << "Child process end by signal: " << signal_number << std::endl;
              } else if (WIFSTOPPED(status)) {
                  int stop_signal = WSTOPSIG(status);
                  std::cerr << "Error child process by signal: " << stop_signal << std::endl;
              } else {
                  std::cerr << "Error child process" << std::endl;
              }
              exit(EXIT_FAILURE);
          }
      }
      
void AlphaZero::_generate_self_play_data(std::string model_path, int iteration, int id_process){

    if (torch::cuda::is_available()) {
        std::cout << "CUDA is available! Training on GPU." << std::endl;
    } else {
        std::cout << "CUDA is not available. Training on CPU." << std::endl;
    }
    torch::Device device = torch::cuda::is_available() ? torch::kCUDA : torch::kCPU;

    std::shared_ptr<BufferEvalManager> buffer_eval_manager = std::make_shared<BufferEvalManager>(game, device, args.batch_size);
    
    try {
        buffer_eval_manager->set_model(model_path);
    }catch (const c10::Error& e) {
        std::cerr << "Error loading model!: " << e.what() << std::endl;
        std::exit(EXIT_FAILURE); 
    }
    std::thread controller_thread([buffer_eval_manager] { buffer_eval_manager->buffer_eval_controller(); });

    std::vector<std::tuple<torch::Tensor, torch::Tensor, torch::Tensor, torch::Tensor>> memory;

    ThreadPool pool(args.num_threads_games);
    std::vector<std::future<std::vector<std::tuple<torch::Tensor, torch::Tensor, torch::Tensor, torch::Tensor>>>> futures;
    for (int i = 0; i < args.n_selfplay_iterations; ++i) {
        futures.emplace_back(
            pool.enqueue([this, buffer_eval_manager, device] { 
                return this->_self_play(buffer_eval_manager, false, device);
            })
        );         
    }

    for (auto& f : futures) {
        auto match_memory = f.get(); 
        memory.insert(memory.end(), match_memory.begin(), match_memory.end());
        //match_memory.clear();
    }

    float steps_avg = memory.size()/args.n_selfplay_iterations;

    this->_save_memory(memory, iteration, id_process);

    buffer_eval_manager->terminate_thread_buffer_eval = true;
    if (controller_thread.joinable()) {
        controller_thread.join(); 
    }
}

void BufferEvalManager::set_model(std::string model_path){
    model = torch::jit::load(model_path); //ERROR HERE
    model.to(device);
    model.eval();
```

My environment:
- OS: Ubuntu 22.04
- Cuda: 12.1
- Torch-TensorRT: 2.2.0
- Libtorch: 2.2.0
