### ISSUE TITLE
🐛 [Bug] Torch_TensorRT build failed on Xavier NX

### ISSUE THREAD

**Issue by Mkath1423** [NVIDIA/Torch-TensorRT#793]
##  Bug Description

After following the steps to compile the package using local sources, the package fails to build. 

I've spent a lot of time trying to get this package working and I'm just stuck here. Any help would be appreciated!

## To Reproduce

1. Pulled L4T ML from NGC
- https://catalog.ngc.nvidia.com/orgs/nvidia/containers/l4t-ml
2.  Ran container 
- sudo docker run -it --network host --gpus all [Image ID]

3. Installed Bazel using instructions in README

4. cloned Torch_TensorRT to root dir

5. Edited WORKSPACE file
- Commented http_archivefor cudnn and tensorrt
- Uncomented local_repository for cudnn and tensorrt
- Changed cuda path to cuda-10.2 instead of cuda-11.3
```
workspace(name = "Torch-TensorRT")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")

http_archive(
    name = "rules_python",
    sha256 = "778197e26c5fbeb07ac2a2c5ae405b30f6cb7ad1f5510ea6fdac03bded96cc6f",
    url = "https://github.com/bazelbuild/rules_python/releases/download/0.2.0/rules_python-0.2.0.tar.gz",
)

load("@rules_python//python:pip.bzl", "pip_install")

http_archive(
    name = "rules_pkg",
    sha256 = "038f1caa773a7e35b3663865ffb003169c6a71dc995e39bf4815792f385d837d",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/rules_pkg/releases/download/0.4.0/rules_pkg-0.4.0.tar.gz",
        "https://github.com/bazelbuild/rules_pkg/releases/download/0.4.0/rules_pkg-0.4.0.tar.gz",
    ],
)

load("@rules_pkg//:deps.bzl", "rules_pkg_dependencies")

rules_pkg_dependencies()

git_repository(
    name = "googletest",
    commit = "703bd9caab50b139428cea1aaff9974ebee5742e",
    remote = "https://github.com/google/googletest",
    shallow_since = "1570114335 -0400",
)

# External dependency for torch_tensorrt if you already have precompiled binaries.
local_repository(
    name = "torch_tensorrt",
    path = "/opt/conda/lib/python3.8/site-packages/torch_tensorrt"
)

# CUDA should be installed on the system locally
new_local_repository(
    name = "cuda",
    build_file = "@//third_party/cuda:BUILD",
    path = "/usr/local/cuda-10.2/",
)

new_local_repository(
    name = "cublas",
    build_file = "@//third_party/cublas:BUILD",
    path = "/usr",
)
#############################################################################################################
# Tarballs and fetched dependencies (default - use in cases when building from precompiled bin and tarballs)
#############################################################################################################

#http_archive(
#    name = "libtorch",
#    build_file = "@//third_party/libtorch:BUILD",
#    sha256 = "190e963e739d5f7c2dcf94b3994de8fcd335706a4ebb333812ea7d8c841beb06",
#    strip_prefix = "libtorch",
#    urls = ["https://download.pytorch.org/libtorch/cu113/libtorch-cxx11-abi-shared-with-deps-1.10.0%2Bcu113.zip"],
#)

#http_archive(
#    name = "libtorch_pre_cxx11_abi",
#    build_file = "@//third_party/libtorch:BUILD",
#    sha256 = "0996a6a4ea8bbc1137b4fb0476eeca25b5efd8ed38955218dec1b73929090053",
#    strip_prefix = "libtorch",
#    urls = ["https://download.pytorch.org/libtorch/cu113/libtorch-shared-with-deps-1.10.0%2Bcu113.zip"],
#)

# Download these tarballs manually from the NVIDIA website
# Either place them in the distdir directory in third_party and use the --distdir flag
# or modify the urls to "file:///<PATH TO TARBALL>/<TARBALL NAME>.tar.gz

#http_archive(
#    name = "cudnn",
#    build_file = "@//third_party/cudnn/archive:BUILD",
#    sha256 = "0e5d2df890b9967efa6619da421310d97323565a79f05a1a8cb9b7165baad0d7",
#    strip_prefix = "cuda",
#    urls = [
#        "https://developer.nvidia.com/compute/machine-learning/cudnn/secure/8.2.4/11.4_20210831/cudnn-11.4-linux-x64-v8.2.4.15.tgz",
#    ],
#)

#http_archive(
#    name = "tensorrt",
#    build_file = "@//third_party/tensorrt/archive:BUILD",
#    sha256 = "3177435024ff4aa5a6dba8c1ed06ab11cc0e1bf3bb712dfa63a43422f41313f3",
#    strip_prefix = "TensorRT-8.0.3.4",
#    urls = [
#        "https://developer.nvidia.com/compute/machine-learning/tensorrt/secure/8.0.3/tars/tensorrt-8.0.3.4.linux.x86_64-gnu.cuda-11.3.cudnn8.2.tar.gz",
#    ],
#)

####################################################################################
# Locally installed dependencies (use in cases of custom dependencies or aarch64)
####################################################################################

# NOTE: In the case you are using just the pre-cxx11-abi path or just the cxx11 abi path
# with your local libtorch, just point deps at the same path to satisfy bazel.

# NOTE: NVIDIA's aarch64 PyTorch (python) wheel file uses the CXX11 ABI unlike PyTorch's standard
# x86_64 python distribution. If using NVIDIA's version just point to the root of the package
# for both versions here and do not use --config=pre-cxx11-abi

new_local_repository(
    name = "libtorch",
    path = "/usr/local/lib/python3.6/dist-packages/torch",
    build_file = "third_party/libtorch/BUILD"
)

new_local_repository(
    name = "libtorch_pre_cxx11_abi",
    path = "/usr/local/lib/python3.6/dist-packages/torch",
    build_file = "third_party/libtorch/BUILD"
)

new_local_repository(
    name = "cudnn",
    path = "/usr/",
    build_file = "@//third_party/cudnn/local:BUILD"
)

new_local_repository(
   name = "tensorrt",
   path = "/usr/",
   build_file = "@//third_party/tensorrt/local:BUILD"
)

#########################################################################
# Testing Dependencies (optional - comment out on aarch64)
#########################################################################
pip_install(
    name = "torch_tensorrt_py_deps",
    requirements = "//py:requirements.txt",
)

pip_install(
    name = "py_test_deps",
    requirements = "//tests/py:requirements.txt",
)

pip_install(
    name = "pylinter_deps",
    requirements = "//tools/linter:requirements.txt",
)
```

4. Ran ```bazel build //:libtorchtrt --platforms //toolchains:jetpack_4.6``` and got the following error

```
root@iris-nx:~/Torch-TensorRT# /root/bazel/output/bazel build //:libtorchtrt --platforms //toolchains:jetpack_4.6
INFO: Build options --compilation_mode and --platforms have changed, discarding analysis cache.
INFO: Analyzed target //:libtorchtrt (2 packages loaded, 2819 targets configured).
INFO: Found 1 target...
ERROR: /root/Torch-TensorRT/core/lowering/BUILD:10:11: Compiling core/lowering/register_trt_placeholder_ops.cpp failed: (Exit 1): gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer '-std=c++0x' -MD -MF ... (remaining 57 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
core/lowering/register_trt_placeholder_ops.cpp:16:34: error: invalid user-defined conversion from 'torch::jit::<lambda(torch::jit::Stack&)>' to 'torch::jit::OperationCreator {aka std::function<void(std::vector<c10::IValue>*)> (*)(const torch::jit::Node*)}' [-fpermissive]
         aliasAnalysisFromSchema()),
                                  ^
core/lowering/register_trt_placeholder_ops.cpp:15:24: note: candidate is: torch::jit::<lambda(torch::jit::Stack&)>::operator void (*)(torch::jit::Stack&)() const <near match>
         [](Stack& stack) { /*noop*/ },
                        ^
core/lowering/register_trt_placeholder_ops.cpp:15:24: note:   no known conversion from 'void (*)(torch::jit::Stack&) {aka void (*)(std::vector<c10::IValue>&)}' to 'torch::jit::OperationCreator {aka std::function<void(std::vector<c10::IValue>*)> (*)(const torch::jit::Node*)}'
In file included from external/libtorch/include/torch/csrc/jit/runtime/custom_operator.h:5:0,
                 from core/lowering/register_trt_placeholder_ops.cpp:1:
external/libtorch/include/torch/csrc/jit/runtime/operator.h:87:3: note:   initializing argument 2 of 'torch::jit::Operator::Operator(std::__cxx11::string, torch::jit::OperationCreator, c10::AliasAnalysisKind)'
   Operator(
   ^~~~~~~~
Target //:libtorchtrt failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 238.094s, Critical Path: 43.61s
INFO: 603 processes: 562 internal, 41 processwrapper-sandbox.
FAILED: Build did NOT complete successfully
root@iris-nx:~/Torch-TensorRT# 
```

## Environment

> Build information about Torch-TensorRT can be found by turning on debug messages

Using NVIDIA L4T ML container from NGC:
 - https://catalog.ngc.nvidia.com/orgs/nvidia/containers/l4t-ml

 - Torch-TensorRT Version (e.g. 1.0.0):
 - PyTorch Version: v1.9.0
 - CPU Architecture: ARMv8
 - OS (e.g., Linux): Jetpack 4.6
 - How you installed PyTorch (`conda`, `pip`, `libtorch`, source): pre installed
 - Build command you used (if compiling from source):  bazel build //:libtorchtrt --compilation_mode opt
 - Are you using local sources or building from archives: local sources
 - Python version: 3.6
 - CUDA version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by narendasan** [comment]
There was a breaking change in PyTorch 1.10.0 that makes versions of Torch-TensorRT targeting 1.10.0 incompatible with previous versions. The easiest solution is to update your version of PyTorch, alternatively trtorch 0.4.0 supports 1.9.0. If neither of these work I can provide more instructions on how to patch 1.0.0 to support 1.9.0

**Comment by Mkath1423** [comment]
I tried installing pytorch 1.10.0 but I keep getting this error when importing it.

Traceback (most recent call last):
  File "setup.py", line 12, in <module>
    from torch.utils import cpp_extension
  File "/usr/local/lib/python3.6/dist-packages/torch/__init__.py", line 196, in <module>
    _load_global_deps()
  File "/usr/local/lib/python3.6/dist-packages/torch/__init__.py", line 149, in _load_global_deps
    ctypes.CDLL(lib_path, mode=ctypes.RTLD_GLOBAL)
  File "/usr/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libcurand.so.10: cannot open shared object file: No such file or directory

I got the whl from here: https://forums.developer.nvidia.com/t/pytorch-for-jetson-version-1-10-now-available/72048

**Comment by Mkath1423** [comment]
I managed to get this to build when running this with torch 1.10 outside of the NGC container. Thanks for the help!

**Comment by dongb5** [comment]
> There was a breaking change in PyTorch 1.10.0 that makes versions of Torch-TensorRT targeting 1.10.0 incompatible with previous versions. The easiest solution is to update your version of PyTorch, alternatively trtorch 0.4.0 supports 1.9.0. If neither of these work I can provide more instructions on how to patch 1.0.0 to support 1.9.0

@narendasan Hi, is it possible to compile libtorchtrt.so of version 1.0.0 with libtorch 1.7.0 on jetpack 4.4?
