### ISSUE TITLE
🐛 [Bug] Running a model that returns a tuple or list of size 2 or greater causes segfault

### ISSUE THREAD

**Issue by chaoz-dev** [NVIDIA/Torch-TensorRT#898]
##  Bug Description

Running a model that returns a tuple (or list) of two or more tensors causes the program to segfault. 
Note that this does NOT occur when returning a tuple of only one tensor. 

Returning a list of only one tensor will throw the following (presumably correct) error:
```
Traceback (most recent call last):                                                                                                
  File "/home/chaoz/av/experimental/chaoz/trtorch/tuple.py", line 34, in <module>                                                                               
    model_trt = torchtrt.compile(                                                                 
  File "/home/chaoz/.anaconda3/envs/trtorch/lib/python3.9/site-packages/torch_tensorrt/_compile.py", line 115, in compile
    return torch_tensorrt.ts.compile(ts_mod, inputs=inputs, enabled_precisions=enabled_precisions, **kwargs)      
  File "/home/chaoz/.anaconda3/envs/trtorch/lib/python3.9/site-packages/torch_tensorrt/ts/_compiler.py", line 116, in compile
    compiled_cpp_mod = _C.compile_graph(module._c, _parse_compile_spec(spec))                      
RuntimeError: [Error thrown at core/conversion/conversion.cpp:220] List type. Only a single tensor or a TensorList type is supported.   
```

## To Reproduce

Run the following (returning input directly to output):
```
  import torch    
  import torch_tensorrt as torchtrt    
      
  import torch_tensorrt.logging as torchtrt_logging    
      
  torchtrt_logging.set_reportable_log_level(torchtrt_logging.Level.Graph)    
      
  torch.manual_seed(0)    
      
  DEVICE = torch.device("cuda:0")    
  SHAPE = (3, 4)    
      
      
  class Model(torch.nn.Module):    
      def __init__(self):    
          super().__init__()    
      
      def forward(self, x):    
          y = x - x    
          z = x + x    
          return (x, z)    
      
      
  if __name__ == "__main__":    
      tensor = torch.randn(SHAPE, dtype=torch.float32, device=DEVICE)    
      
      model = Model().eval().to(DEVICE)    
      out = model(tensor)    
      print(out)    
      
      model_trt = torchtrt.compile(    
          model,    
          inputs=[    
              torchtrt.Input(shape=SHAPE),    
          ],    
          enabled_precisions={torch.float},    
      )    
      out_trt = model(tensor)    
      print(out_trt)    
      
      assert torch.max(torch.abs(out - out_trt)) < 1e-6    

```
This produces the following output (using `Info` level logging):
```
(trtorch) ~/av/experimental/chaoz/trtorch (chaoz/torch-tensorrt-modules) $ python tuple.py
(tensor([[-0.9247, -0.4253, -2.6438,  0.1452],
        [-0.1209, -0.5797, -0.6229, -0.3284],
        [-1.0745, -0.3631, -1.6711,  2.2655]], device='cuda:0'), tensor([[-1.8493, -0.8507, -5.2877,  0.2904],
        [-0.2417, -1.1595, -1.2457, -0.6568],
        [-2.1491, -0.7263, -3.3421,  4.5310]], device='cuda:0'))
INFO: [Torch-TensorRT] - ir was set to default, using TorchScript as ir
INFO: [Torch-TensorRT] - Module was provided as a torch.nn.Module, trying to script the module with torch.jit.script. In the event of a failure please preconvert your module to TorchScript
INFO: [Torch-TensorRT] - Lowered Graph: graph(%x.1 : Tensor):
  %2 : int = prim::Constant[value=1]()
  %z.1 : Tensor = aten::add(%x.1, %x.1, %2) # /home/chaoz/av/experimental/chaoz/trtorch/tuple.py:23:12
  return (%x.1, %z.1)

Segmentation fault (core dumped)
```

Run the following (all outputs have been operated on):
```
  import torch
  import torch_tensorrt as torchtrt
  
  
  import torch_tensorrt.logging as torchtrt_logging
  
  torchtrt_logging.set_reportable_log_level(torchtrt_logging.Level.Info)
  
  torch.manual_seed(0)
  
  DEVICE = torch.device("cuda:0")
  SHAPE = (3, 4)
  
  
  class Model(torch.nn.Module):
      def __init__(self):
          super().__init__()
  
      def forward(self, x):
          y = x - x
          z = x + x
          return (y, z)
  
  
  if __name__ == "__main__":
      tensor = torch.randn(SHAPE, dtype=torch.float32, device=DEVICE)
  
      model = Model().eval().to(DEVICE)
      out = model(tensor)
      print(out)
  
      model_trt = torchtrt.compile(
          model,
          inputs=[
              torchtrt.Input(shape=SHAPE),
          ],
          enabled_precisions={torch.float},
      )
      out_trt = model(tensor)
      print(out_trt)
  
      assert torch.max(torch.abs(out - out_trt)) < 1e-6
```
This produces the following output (using `Info` level logging):
```
(trtorch-1.0) ~/av/experimental/chaoz/trtorch (chaoz/torch-tensorrt-modules) $ python tuple.py
(tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]], device='cuda:0'), tensor([[-1.8493, -0.8507, -5.2877,  0.2904],
        [-0.2417, -1.1595, -1.2457, -0.6568],
        [-2.1491, -0.7263, -3.3421,  4.5310]], device='cuda:0'))
INFO: [Torch-TensorRT] - ir was set to default, using TorchScript as ir
INFO: [Torch-TensorRT] - Module was provided as a torch.nn.Module, trying to script the module with torch.jit.script. In the event of a failure please preconvert your module to TorchScript
INFO: [Torch-TensorRT] - Lowered Graph: graph(%x.1 : Tensor):
  %2 : int = prim::Constant[value=1]()
  %y.1 : Tensor = aten::sub(%x.1, %x.1, %2) # /home/chaoz/av/experimental/chaoz/trtorch/tuple.py:23:12
  %z.1 : Tensor = aten::add(%x.1, %x.1, %2) # /home/chaoz/av/experimental/chaoz/trtorch/tuple.py:24:12
  return (%y.1, %z.1)

Segmentation fault (core dumped)
```

## Expected behavior

We expect the run to either complete, or error out because the tuple type is unsupported.

## Environment

> Build information about Torch-TensorRT can be found by turning on debug messages

 - Torch-TensorRT Version (e.g. 1.0.0): Master commit `ef62f6bf26e1e282eccfb8f04e38a2b22558420b` (latest as of this writing); also appears in 1.0 release.
 - PyTorch Version (e.g. 1.0): 1.10.2
 - CPU Architecture: x86-64
 - OS (e.g., Linux): Ubuntu 18.04
 - How you installed PyTorch (`conda`, `pip`, `libtorch`, source): conda
 - Build command you used (if compiling from source):
 - Are you using local sources or building from archives: local sources 
 - Python version: 3.9
 - CUDA version: 11.6
 - GPU models and configuration: NVIDIA A10
 - Any other relevant information: 
Driver Version: 510.47.03
TRT Version: 8.2.3.0
cuDNN Version: 8.3.2.44

## Additional context
This issue is very high priority for us, as all of our models return multiple tensors and at minimum will use tuples/lists to do so.

**Comment by chaoz-dev** [comment]
Not sure if tuple is expected to be supported right now; this might be an issue related to #428

**Comment by narendasan** [comment]
Tuples should be supported outputs, iirc, the SSD network example returns a tuple output. If I had to guess there might be some issues due to the fact that you are directly returning an input with no operations. @peri044 I thought we addressed this but maybe we didn't look at the graph construction stage properly.

**Comment by chaoz-dev** [comment]
Ah do add and subtract not count as explicit ops here? I can test with a different op and see what the output is... one moment.

**Comment by chaoz-dev** [comment]
Ah apologies that's a typo on my part. I've updated so that `forward` is returning `(y, z)` now (so both outputs have been operated on), but the same error occurs; I'll update the above ticket with the fixed outputs.

**Comment by chaoz-dev** [comment]
Also FYI, looks like this error is also present in the 1.0 release.

**Comment by chaoz-dev** [comment]
Aha, I suspect that there might a double free somewhere or dup memory access here as a result of reusing the input for two outputs (even after operating on them). The following appears to run without issues:
```
  import torch
  import torch_tensorrt as torchtrt
  
  
  import torch_tensorrt.logging as torchtrt_logging
  
  torchtrt_logging.set_reportable_log_level(torchtrt_logging.Level.Info)
  
  torch.manual_seed(0)
  
  DEVICE = torch.device("cuda:0")
  SHAPE = (3, 4)
  
  
  class Model(torch.nn.Module):
      def __init__(self):
          super().__init__()
  
      def forward(self, x, y):
          a = x + x
          b = y + y
          return (a, b)
  
  
  if __name__ == "__main__":
      tensor = torch.randn(SHAPE, dtype=torch.float32, device=DEVICE)
  
      model = Model().eval().to(DEVICE)
      out = model(tensor, tensor)
      print(out)
  
      model_trt = torchtrt.compile(
          model,
          inputs=[
              torchtrt.Input(shape=SHAPE),
              torchtrt.Input(shape=SHAPE),
          ],
          enabled_precisions={torch.float},
      )
      out_trt = model(tensor, tensor)
      print(out_trt)
  
      assert torch.max(torch.abs(out[0] - out_trt[0])) < 1e-6
      assert torch.max(torch.abs(out[1] - out_trt[1])) < 1e-6
```
Note the forward function here:
```
      def forward(self, x, y):
          a = x + x
          b = y + y
          return (a, b)
```
This outputs the following (correctly):
```
(trtorch-1.0) ~/av/experimental/chaoz/trtorch (chaoz/torch-tensorrt-modules) $ python tuple.py
(tensor([[-1.8493, -0.8507, -5.2877,  0.2904],
        [-0.2417, -1.1595, -1.2457, -0.6568],
        [-2.1491, -0.7263, -3.3421,  4.5310]], device='cuda:0'), tensor([[-1.8493, -0.8507, -5.2877,  0.2904],
        [-0.2417, -1.1595, -1.2457, -0.6568],
        [-2.1491, -0.7263, -3.3421,  4.5310]], device='cuda:0'))
INFO: [Torch-TensorRT] - ir was set to default, using TorchScript as ir
INFO: [Torch-TensorRT] - Module was provided as a torch.nn.Module, trying to script the module with torch.jit.script. In the event of a failure please preconvert your module to TorchScript
INFO: [Torch-TensorRT] - Lowered Graph: graph(%x.1 : Tensor,
      %y.1 : Tensor):
  %3 : int = prim::Constant[value=1]()
  %a.1 : Tensor = aten::add(%x.1, %x.1, %3) # /home/chaoz/av/experimental/chaoz/trtorch/tuple.py:22:12
  %b.1 : Tensor = aten::add(%y.1, %y.1, %3) # /home/chaoz/av/experimental/chaoz/trtorch/tuple.py:23:12
  return (%a.1, %b.1)

WARNING: [Torch-TensorRT] - Cannot infer input type from calcuations in graph for input x.1. Assuming it is Float32. If not, specify input type explicity
WARNING: [Torch-TensorRT] - Cannot infer input type from calcuations in graph for input y.1. Assuming it is Float32. If not, specify input type explicity
INFO: [Torch-TensorRT] - Skipping partitioning since model is fully supported
INFO: [Torch-TensorRT TorchScript Conversion Context] - [MemUsageChange] Init CUDA: CPU +448, GPU +0, now: CPU 3411, GPU 1873 (MiB)
INFO: [Torch-TensorRT TorchScript Conversion Context] - [MemUsageSnapshot] Begin constructing builder kernel library: CPU 3411 MiB, GPU 1873 MiB
INFO: [Torch-TensorRT TorchScript Conversion Context] - [MemUsageSnapshot] End constructing builder kernel library: CPU 3565 MiB, GPU 1915 MiB
INFO: [Torch-TensorRT] - Settings requested for TensorRT engine:
    Enabled Precisions: Float32
    TF32 Floating Point Computation Enabled: 1
    Truncate Long and Double: 0
    Make Refittable Engine: 0
    Debuggable Engine: 0
    Strict Types: 0
    GPU ID: 0
    Allow GPU Fallback (if running on DLA): 0
    Min Timing Iterations: 2
    Avg Timing Iterations: 1
    Max Workspace Size: 1073741824
    Max Batch Size: Not set
    Device Type: GPU
    GPU ID: 0
    Engine Capability: standard
    Calibrator Created: 0
INFO: [Torch-TensorRT TorchScript Conversion Context] - Converting Block
INFO: [Torch-TensorRT TorchScript Conversion Context] - Adding Input x.1 (named: input_0): Input(shape: [3, 4], dtype: Float32, format: NCHW\Contiguous\Linear) in engine (conversion.AddInputs)
INFO: [Torch-TensorRT TorchScript Conversion Context] - Adding Input y.1 (named: input_1): Input(shape: [3, 4], dtype: Float32, format: NCHW\Contiguous\Linear) in engine (conversion.AddInputs)
INFO: [Torch-TensorRT TorchScript Conversion Context] - Adding Layer %a.1 : Tensor = aten::add(%x.1, %x.1, %3) # /home/chaoz/av/experimental/chaoz/trtorch/tuple.py:22:12 (ctx.AddLayer)
INFO: [Torch-TensorRT TorchScript Conversion Context] - Adding Layer %b.1 : Tensor = aten::add(%y.1, %y.1, %3) # /home/chaoz/av/experimental/chaoz/trtorch/tuple.py:23:12 (ctx.AddLayer)
INFO: [Torch-TensorRT TorchScript Conversion Context] - Marking Output a.1 named output_0 in engine (ctx.MarkOutput)
INFO: [Torch-TensorRT TorchScript Conversion Context] - Marking Output b.1 named output_1 in engine (ctx.MarkOutput)
WARNING: [Torch-TensorRT TorchScript Conversion Context] - TensorRT was linked against cuBLAS/cuBLAS LT 11.6.5 but loaded cuBLAS/cuBLAS LT 11.5.1
INFO: [Torch-TensorRT TorchScript Conversion Context] - [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +747, GPU +320, now: CPU 4312, GPU 2235 (MiB)
INFO: [Torch-TensorRT TorchScript Conversion Context] - [MemUsageChange] Init cuDNN: CPU +126, GPU +58, now: CPU 4438, GPU 2293 (MiB)
INFO: [Torch-TensorRT TorchScript Conversion Context] - Local timing cache in use. Profiling results in this builder pass will not be stored.
INFO: [Torch-TensorRT TorchScript Conversion Context] - Detected 2 inputs and 2 output network tensors.
INFO: [Torch-TensorRT TorchScript Conversion Context] - Total Host Persistent Memory: 0
INFO: [Torch-TensorRT TorchScript Conversion Context] - Total Device Persistent Memory: 0
INFO: [Torch-TensorRT TorchScript Conversion Context] - Total Scratch Memory: 0
INFO: [Torch-TensorRT TorchScript Conversion Context] - [MemUsageStats] Peak memory usage of TRT CPU/GPU memory allocators: CPU 0 MiB, GPU 4 MiB
INFO: [Torch-TensorRT TorchScript Conversion Context] - Total Activation Memory: 0
WARNING: [Torch-TensorRT TorchScript Conversion Context] - TensorRT was linked against cuBLAS/cuBLAS LT 11.6.5 but loaded cuBLAS/cuBLAS LT 11.5.1
INFO: [Torch-TensorRT TorchScript Conversion Context] - [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +0, GPU +8, now: CPU 4438, GPU 2301 (MiB)
INFO: [Torch-TensorRT TorchScript Conversion Context] - [MemUsageChange] Init cuDNN: CPU +0, GPU +8, now: CPU 4438, GPU 2309 (MiB)
INFO: [Torch-TensorRT TorchScript Conversion Context] - [MemUsageChange] TensorRT-managed allocation in building engine: CPU +0, GPU +0, now: CPU 0, GPU 0 (MiB)
INFO: [Torch-TensorRT] - [MemUsageChange] Init CUDA: CPU +0, GPU +0, now: CPU 4285, GPU 2249 (MiB)
INFO: [Torch-TensorRT] - Loaded engine size: 0 MiB
WARNING: [Torch-TensorRT] - TensorRT was linked against cuBLAS/cuBLAS LT 11.6.5 but loaded cuBLAS/cuBLAS LT 11.5.1
INFO: [Torch-TensorRT] - [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +0, GPU +10, now: CPU 4285, GPU 2259 (MiB)
INFO: [Torch-TensorRT] - [MemUsageChange] Init cuDNN: CPU +0, GPU +8, now: CPU 4285, GPU 2267 (MiB)
INFO: [Torch-TensorRT] - [MemUsageChange] TensorRT-managed allocation in engine deserialization: CPU +0, GPU +0, now: CPU 0, GPU 0 (MiB)
WARNING: [Torch-TensorRT] - TensorRT was linked against cuBLAS/cuBLAS LT 11.6.5 but loaded cuBLAS/cuBLAS LT 11.5.1
INFO: [Torch-TensorRT] - [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +0, GPU +10, now: CPU 4285, GPU 2259 (MiB)
INFO: [Torch-TensorRT] - [MemUsageChange] Init cuDNN: CPU +0, GPU +8, now: CPU 4285, GPU 2267 (MiB)
INFO: [Torch-TensorRT] - [MemUsageChange] TensorRT-managed allocation in IExecutionContext creation: CPU +0, GPU +0, now: CPU 0, GPU 0 (MiB)
(tensor([[-1.8493, -0.8507, -5.2877,  0.2904],
        [-0.2417, -1.1595, -1.2457, -0.6568],
        [-2.1491, -0.7263, -3.3421,  4.5310]], device='cuda:0'), tensor([[-1.8493, -0.8507, -5.2877,  0.2904],
        [-0.2417, -1.1595, -1.2457, -0.6568],
        [-2.1491, -0.7263, -3.3421,  4.5310]], device='cuda:0'))
```

**Comment by chaoz-dev** [comment]
The seg fault occurs again with the following forward definition (same script as above otherwise):
```
      def forward(self, x, y):    
          a = x + x - y    
          b = y + y    
          return (a, b)    
```

**Comment by chaoz-dev** [comment]
The seg fault does _not_ occur with the following forward definition (same script as before otherwise):
```
      def forward(self, x, y):
          a = x + x
          b = y + y - a
          return (a, b)
```

**Comment by chaoz-dev** [comment]
Oh, a question regarding this error: 
```
RuntimeError: [Error thrown at core/conversion/conversion.cpp:220] List type. Only a single tensor or a TensorList type is supported.   
```
Sounds like `list` is not yet currently supported as an output type?

**Comment by chaoz-dev** [comment]
Ah, looks like it's a potential issue with how the list is created... I can return a list of tensors as long as I do not perform any operations on the tensors, but applying ops to the tensors will cause the list return to fail. I'll open up a new ticket with regards to this.

**Comment by ashafaei** [comment]
I also spent a good hour on this problem. I'm almost sure the output list is not constructed correctly after it's compiled with TensorRT. If you print the graph/code just before compilation and then compare it with the compiled version, you'll see that the original traced model is constructing the output in a different way than the compiled one. I'm using the NGC's PyTorch, and I kept getting
```
Method (but not graphs in general) require a single output. Use None/Tuple for 0 or 2+ outputs
```
on the compiled version, but the original traced model was working fine.

**Comment by chaoz-dev** [comment]
Ah this is interesting, could you post a snippet or example graph that demonstrates this issue? I'd be curious to see what the conditions are for generating this error.

**Comment by narendasan** [comment]
@chaoz-dev When I run any of the repros on master, the only issue I get is for the original one that you cant subtract two tuples, but for either of the segfault causes the graph gets complied properly and I see the tuple construct in the graph as expected. 

This is with commit ef62f6bf26e1e282eccfb8f04e38a2b22558420b

The differences I am seeing are in the system: I am using CUDA 11.3 (which is the target version for pytorch.org pytorch), TensorRT 8.2.2.1, and cuDNN 8.2.4.15. Are you using an NGC container release?

**Comment by ashafaei** [comment]
I was using `nvcr.io/nvidia/pytorch:22.01-py3` on `Driver Version: 510.47.03    CUDA Version: 11.6`. I see that `nvcr.io/nvidia/pytorch:22.02-py3` is also [available now](https://docs.nvidia.com/deeplearning/frameworks/pytorch-release-notes/rel_22-02.html#rel_22-02). I ran my test again with the new image.

The network returns 12 tensors as a tuple (I also tried OrderedDicts etc.) The original traced model produces all 12 tensors correctly, however, after I compile with TensorRT I get this error:

```
Method (but not graphs in general) require a single output. Use None/Tuple for 0 or 2+ outputs
```

The graph of the original traced model ends like below

```
  %923 : (Float(1, 2, 129, 86, strides=[22188, 11094, 86, 1], requires_grad=0, device=cuda:0), Float(1, 4, 129, 86, strides=[44376, 11094, 86, 1], requires_grad=0, device=cuda:0), Float(1, 2, 64, 43, strides=[5504, 2752, 43, 1], requires_grad=0, device=cuda:0), Float(1, 4, 64, 43, strides=[11008, 2752, 43, 1], requires_grad=0, device=cuda:0), Float(1, 2, 32, 21, strides=[1344, 672, 21, 1], requires_grad=0, device=cuda:0), Float(1, 4, 32, 21, strides=[2688, 672, 21, 1], requires_grad=0, device=cuda:0), Float(1, 2, 20, 14, strides=[560, 280, 14, 1], requires_grad=0, device=cuda:0), Float(1, 4, 20, 14, strides=[1120, 280, 14, 1], requires_grad=0, device=cuda:0), Float(1, 2, 10, 7, strides=[140, 70, 7, 1], requires_grad=0, device=cuda:0), Float(1, 4, 10, 7, strides=[280, 70, 7, 1], requires_grad=0, device=cuda:0), Float(1, 2, 5, 4, strides=[40, 20, 4, 1], requires_grad=0, device=cuda:0), Float(1, 4, 5, 4, strides=[80, 20, 4, 1], requires_grad=0, device=cuda:0)) = prim::TupleConstruct(%1111, %1112, %1113, %1114, %1115, %1116, %1117, %1118, %1119, %1120, %1121, %1122)
  return (%923)
```

I don't know much about this language, but it appears that the original traced model is creating a `TupleConstruct` and returning that. However, the tensort-RT compiled model does this:

```
  %23 : Tensor[] = prim::ListConstruct(%10, %14, %c1, %16, %6, %13, %5, %12, %15)
  %24 : Tensor[] = tensorrt::execute_engine(%23, %__torch___s3fd_wrapper_trt_engine_0x55a9fb97a2c0)
  %25 : Tensor, %26 : Tensor, %27 : Tensor, %28 : Tensor, %29 : Tensor, %30 : Tensor, %31 : Tensor, %32 : Tensor = prim::ListUnpack(%24)
  return (%27, %8, %28, %26, %31, %25, %32, %7, %29, %9, %30, %17)
```

which appears to be an explicit unpacking of the list and returning that instead, which later triggers the above error in the Pytorch engine.

I'm no sure if this is helpful, but I could clean up the code to create a minimal setup to reproduce this by the end of the week.

**Comment by chaoz-dev** [comment]
> @chaoz-dev When I run any of the repros on master, the only issue I get is for the original one that you cant subtract two tuples, but for either of the segfault causes the graph gets complied properly and I see the tuple construct in the graph as expected.

Ah this was run using a conda environment with the above configurations. Let me give this a try using the NGC container...

**Comment by ashafaei** [comment]
> Repro would be useful, seems like a slightly different error but would be interested to see what is happening here.

@narendasan thanks for the reply. I noticed that there's already a documented version of the problem here #899 .

**Comment by chaoz-dev** [comment]
@narendasan Using the `pytorch:21.11-py3` NGC container, I'm running the following script: 
```

**Comment by chaoz-dev** [comment]
@narendasan Using the `pytorch:21.11-py3` NGC container (with Torch-TensorRT 1.0), I'm running the following script (this just addresses the tuple subtraction issue that you mentioned; it is otherwise the same as in the listed example):
```
  import torch    
  import torch_tensorrt as torchtrt    
      
      
  import torch_tensorrt.logging as torchtrt_logging    
      
  torchtrt_logging.set_reportable_log_level(torchtrt_logging.Level.Info)    
      
  torch.manual_seed(0)    
      
  DEVICE = torch.device("cuda:0")    
  SHAPE = (3, 4)    
      
      
  class Model(torch.nn.Module):    
      def __init__(self):    
          super().__init__()    
      
      def forward(self, x):    
          a = x + x    
          b = x - x    
          return (a, b)    
      
      
  if __name__ == "__main__":    
      tensor = torch.randn(SHAPE, dtype=torch.float32, device=DEVICE)    
      
      model = Model().eval().to(DEVICE)    
      out = model(tensor)    
      print(f'Model: {out}')    
      
      model_trt = torchtrt.compile(    
          model,    
          inputs=[    
              torchtrt.Input(shape=SHAPE),    
          ],    
          enabled_precisions={torch.float},    
      )    
      out_trt = model(tensor)    
      print(f'Model TRT: {out_trt}')    
      
      assert torch.max(torch.abs(out[0] - out_trt[0])) < 1e-6    
      assert torch.max(torch.abs(out[1] - out_trt[1])) < 1e-6    
```

Running the container interactively, I'm still seeing the segfault unfortunately:
```
$ docker run --gpus all --rm  -it -v $(pwd):/scripts:ro nvcr.io/nvidia/pytorch:21.11-py3
...
root@8ae595ddc1e0:/workspace# python /scripts/tuple.py 
Model: (tensor([[-1.8493, -0.8507, -5.2877,  0.2904],
        [-0.2417, -1.1595, -1.2457, -0.6568],
        [-2.1491, -0.7263, -3.3421,  4.5310]], device='cuda:0'), tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]], device='cuda:0'))
INFO: [Torch-TensorRT] - ir was set to default, using TorchScript as ir
INFO: [Torch-TensorRT] - Module was provided as a torch.nn.Module, trying to script the module with torch.jit.script. In the event of a failure please preconvert your module to TorchScript
INFO: [Torch-TensorRT] - Lowered Graph: graph(%x.1 : Tensor):
  %2 : int = prim::Constant[value=1]()
  %a.1 : Tensor = aten::add(%x.1, %x.1, %2) # /scripts/tuple.py:22:12
  %b.1 : Tensor = aten::sub(%x.1, %x.1, %2) # /scripts/tuple.py:23:12
  return (%a.1, %b.1)

Segmentation fault (core dumped)
```

**Comment by chaoz-dev** [comment]
Let me try with a newer container...

**Comment by chaoz-dev** [comment]
Hmmm tried with the newest container `22.02-py3`, but I'm still seeing the issue:

With the same script as before, here's what I'm running:
```
docker run --gpus all --rm  -it -v $(pwd):/scripts:ro nvcr.io/nvidia/pytorch:22.02-py3
...
root@33468191a29c:/workspace# python /scripts/tuple.py
Model: (tensor([[-1.8493, -0.8507, -5.2877,  0.2904],
        [-0.2417, -1.1595, -1.2457, -0.6568],
        [-2.1491, -0.7263, -3.3421,  4.5310]], device='cuda:0'), tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]], device='cuda:0'))
INFO: [Torch-TensorRT] - ir was set to default, using TorchScript as ir
INFO: [Torch-TensorRT] - Module was provided as a torch.nn.Module, trying to script the module with torch.jit.script. In the event of a failure please preconvert your module to TorchScript
INFO: [Torch-TensorRT] - Lowered Graph: graph(%x.1 : Tensor):
  %2 : int = prim::Constant[value=1]()
  %a.1 : Tensor = aten::add(%x.1, %x.1, %2) # /scripts/tuple.py:22:12
  %b.1 : Tensor = aten::sub(%x.1, %x.1, %2) # /scripts/tuple.py:23:12
  return (%a.1, %b.1)

Segmentation fault (core dumped)
```

**Comment by chaoz-dev** [comment]
Wonder if my local configurations are affecting things within the Docker container as well... although I thought the NGC containers should be self contained such that the system configurations shouldn't matter?

**Comment by narendasan** [comment]
@peri044 Can you try to replicate this, I am not sure why it works fine on my system

**Comment by ashafaei** [comment]
@narendasan @chaoz-dev I'm running `nvcr.io/nvidia/pytorch:22.02-py3` which has `TRT_VERSION="8.2.3.0+cuda11.4.2.006"` running with `CUDA Version: 11.6` and `Driver Version: 510.47.03` on a `3090` GPU. The script does not trigger a seg-fault.
Yesterday I was trying to get another architecture work and I got seg-faults when I passed the vanilla torch.nn.Module model for compilation (so it's traced using tensorRT first). But I remember if I traced it manually and tried to compile it, it would fail, but wouldn't trigger a seg-fault. This is potentially another issue, and I will document it the next time I encounter it for sure. I'm just saying that even though I don't get seg-fault on this particular instance, I have had it before.

**Comment by peri044** [comment]
> Hmmm tried with the newest container `22.02-py3`, but I'm still seeing the issue:
> 
> With the same script as before, here's what I'm running:
> 
> ```
> docker run --gpus all --rm  -it -v $(pwd):/scripts:ro nvcr.io/nvidia/pytorch:22.02-py3
> ...
> root@33468191a29c:/workspace# python /scripts/tuple.py
> Model: (tensor([[-1.8493, -0.8507, -5.2877,  0.2904],
>         [-0.2417, -1.1595, -1.2457, -0.6568],
>         [-2.1491, -0.7263, -3.3421,  4.5310]], device='cuda:0'), tensor([[0., 0., 0., 0.],
>         [0., 0., 0., 0.],
>         [0., 0., 0., 0.]], device='cuda:0'))
> INFO: [Torch-TensorRT] - ir was set to default, using TorchScript as ir
> INFO: [Torch-TensorRT] - Module was provided as a torch.nn.Module, trying to script the module with torch.jit.script. In the event of a failure please preconvert your module to TorchScript
> INFO: [Torch-TensorRT] - Lowered Graph: graph(%x.1 : Tensor):
>   %2 : int = prim::Constant[value=1]()
>   %a.1 : Tensor = aten::add(%x.1, %x.1, %2) # /scripts/tuple.py:22:12
>   %b.1 : Tensor = aten::sub(%x.1, %x.1, %2) # /scripts/tuple.py:23:12
>   return (%a.1, %b.1)
> 
> Segmentation fault (core dumped)
> ```

Hmm.. I see some strange behavior. Outside the container, this runs fine for me (latest master with Torch 1.10.0 + cuda 11.3). But inside the container 22.02, I see a seg fault.

**Comment by peri044** [comment]
I see MarkOutput changes b/w master branch and release/ngc/22.02 branch. The change is https://github.com/NVIDIA/Torch-TensorRT/blob/master/core/conversion/conversion.cpp#L242-L253. Although this doesn't seem to be executing particularly for this subtraction example, there might be other differences b/w these two branches which might be causing this. Can you try building a docker container based on master by following https://github.com/NVIDIA/Torch-TensorRT/tree/master/docker#build-container and running the script inside it ?

**Comment by chaoz-dev** [comment]
Hmm tried building a docker container using the aforementioned instructions, but I seem to be getting an error; from the root of the Torch-TensorRT repo, I'm running the following:
```
docker build --build-arg BASE=22.02 -f docker/Dockerfile -t torch_tensorrt1.0:latest .
```

but I'm seeing the following error:
```
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
Loading: 
Loading: 0 packages loaded
Analyzing: target //:libtorchtrt (1 packages loaded)
Analyzing: target //:libtorchtrt (1 packages loaded, 0 targets configured)
Analyzing: target //:libtorchtrt (35 packages loaded, 75 targets configured)
INFO: Analyzed target //:libtorchtrt (43 packages loaded, 8521 targets configured).

INFO: Found 1 target...
[0 / 124] [Prepa] Creating source manifest for @rules_pkg//:build_tar
ERROR: /root/.cache/bazel/_bazel_root/67e780960d5a9319501f4e5a06fc77dc/external/libtorch/BUILD.bazel:88:11: SolibSymlink _solib_k8/_U@libtorch_S_S_Ccaffe2___Ulib/libcaffe2_module_test_dynamic.so failed: missing input file 'external/libtorch/lib/libcaffe2_module_test_dynamic.so', owner: '@libtorch//:lib/libcaffe2_module_test_dynamic.so'
Target //:libtorchtrt failed to build
Use --verbose_failures to see the command lines of failed build steps.
ERROR: /root/.cache/bazel/_bazel_root/67e780960d5a9319501f4e5a06fc77dc/external/libtorch/BUILD.bazel:88:11 SolibSymlink _solib_k8/_U@libtorch_S_S_Ccaffe2___Ulib/libcaffe2_module_test_dynamic.so failed: 1 input file(s) do not exist
INFO: Elapsed time: 7.763s, Critical Path: 0.03s
INFO: 481 processes: 481 internal.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully
```

Looks like I'm missing a shared object file here... do we expect this to be in the docker base image?

**Comment by narendasan** [comment]
Can you try basing on 21.10. this is likely because 1.11.0 is what is shipped in later containers and the libraries have changed

**Comment by chaoz-dev** [comment]
Think I managed to get it to work -- 
Pulled the latest TensorRT NGC container (`nvcr.io/nvidia/tensorrt:22.02-py3`), pip installed PyTorch 1.10, and built the repo from source within the container. Running the above script now no longer causes a segfault, so I assume the issue was as you described, a mismatch in shipped libraries.

**Comment by chaoz-dev** [comment]
Some more data -- it looks like the segfault still occurs on the 1.0 release using the aforementioned configurations. Might need to go back to an earlier TRT NGC container.
