### ISSUE TITLE
🐛 [Bug] Bitwise operators on `bool` dtype tensors throws error: `RuntimeError: [Error thrown at core/ir/ir.cpp:17] Expected vals.size() == specs.size() to be true but got false`

### ISSUE THREAD

**Issue by chaoz-dev** [NVIDIA/Torch-TensorRT#911]
##  Bug Description
Running bitwise operators on two `bool` dtype tensors throws error 
```
RuntimeError: [Error thrown at core/ir/ir.cpp:17] Expected vals.size() == specs.size() to be true but got false
Expected dimension specifications for all input tensors, but found 2 input tensors and 1 dimension specs
```
This does not appear to be an invalid op however, when run through a non-TRT model.

## To Reproduce
```
  import torch
  import torch_tensorrt as torchtrt
  
  
  import torch_tensorrt.logging as logging
  
  logging.set_reportable_log_level(logging.Level.Warning)
  
  torch.manual_seed(0)
  
  DEVICE = torch.device("cuda:0")
  SHAPE = (1, 2)
  
  
  class Model(torch.nn.Module):
      def __init__(self):
          super().__init__()
  
      def forward(self, a, b):
          return a | b
  
  
  if __name__ == "__main__":
      tensor = torch.ones(SHAPE, dtype=torch.bool, device=DEVICE)
      zeros = torch.zeros(SHAPE, dtype=torch.bool, device=DEVICE)
  
      model = Model().eval().to(DEVICE)
      out = model(tensor, zeros)
      print(f"Model: {out}")
  
      model_trt = torchtrt.compile(
          model,
          inputs=[
              torchtrt.Input(shape=SHAPE),
          ],
          enabled_precisions={torch.float},
      )
      out_trt = model(tensor, zeros)
      print(f"Model TRT: {out_trt}")
```

Outputs the following:
```
root@c32cd58cec87:/workspace# python /scripts/bitwise.py
Model: tensor([[True, True]], device='cuda:0')
Traceback (most recent call last):
  File "/scripts/bitwise.py", line 33, in <module>
    model_trt = torchtrt.compile(
  File "/opt/conda/lib/python3.8/site-packages/torch_tensorrt/_compile.py", line 97, in compile
    return torch_tensorrt.ts.compile(ts_mod, inputs=inputs, enabled_precisions=enabled_precisions, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch_tensorrt/ts/_compiler.py", line 119, in compile
    compiled_cpp_mod = _C.compile_graph(module._c, _parse_compile_spec(spec))
RuntimeError: [Error thrown at core/ir/ir.cpp:17] Expected vals.size() == specs.size() to be true but got false
Expected dimension specifications for all input tensors, but found 2 input tensors and 1 dimension specs
```

## Expected behavior
Output should be similar to the non-TRT version and should not throw a runtime error:
```
Model: tensor([[True, True]], device='cuda:0')
```

## Environment
NGC containers `21.11-py3` and `22.02-py3` on Ubuntu 18.04 x86-64.

**Comment by peri044** [comment]
I modified your script to compile it this way. Setting the number of inputs and their dtypes respectively,
```
 model_trt = torchtrt.compile(
      model,
      inputs=[
          torchtrt.Input(shape=SHAPE, dtype=torch.bool), torchtrt.Input(shape=SHAPE, dtype=torch.bool),
      ],
      enabled_precisions={torch.float},
  )
```
It results in a different error 
```
  File "chao.py", line 20, in forward
  def forward(self, a, b):
      return a | b
             ~~~~~ <--- HERE
RuntimeError: "bitwise_or_cuda" not implemented for 'Float'
```
This error is again coming from shape_analysis.cpp https://github.com/NVIDIA/Torch-TensorRT/blob/release/ngc/22.02/core/partitioning/shape_analysis.cpp#L92
The dtype passed for the dummy inputs in the shape analysis is float (which is wrong. It should be bool). We'll work on fixing this.

**Comment by peri044** [comment]
Upon more debugging and adding some on the fly fixes 
Fix 1 : https://github.com/NVIDIA/Torch-TensorRT/blob/master/core/ir/Input.cpp#L51 Bool input type should return true 
Fix 2 : https://github.com/NVIDIA/Torch-TensorRT/blob/master/core/ir/Input.cpp#L43 Add the following snippet to  support bool dtype and format 
```
  case nvinfer1::DataType::kBOOL: // Supports Linear (NCHW)
      switch (format) {
        case nvinfer1::TensorFormat::kLINEAR:
          return true;
        default:
          return false;
      }
```
After these additions, the main problem is the graph is unable to infer dtypes from input. 
```
GRAPH: Node we are looking at: %3 : Tensor = aten::__or__(%a.1, %b.1) # chao.py:20:13
GRAPH: Node %3 : Tensor = aten::__or__(%a.1, %b.1) # chao.py:20:13 outputs a tensor
GRAPH: All inputs to Node %3 : Tensor = aten::__or__(%a.1, %b.1) # chao.py:20:13 are graph inputs, cannot be used to determine input type
GRAPH: Node we are looking at:  = prim::Return(%3)
GRAPH: Node  = prim::Return(%3) does not output a tensor, skipping
GRAPH: Cannot determine input types from graph
```
This function returns empty  https://github.com/NVIDIA/Torch-TensorRT/blob/master/core/ir/ir.cpp#L48 (ideally it should return bool ). 
So the shape analysis dummy inputs assume float since it is the default.

**Comment by narendasan** [comment]
> Fix 1 : https://github.com/NVIDIA/Torch-TensorRT/blob/master/core/ir/Input.cpp#L51 Bool input type should return **true**
Can we take bool tensors in as an input for TensorRT?

**Comment by chaoz-dev** [comment]
Just tested this using NGC `nvcr.io/nvidia/tensorrt:22.03-py3` using latest master commit `7330c4`, but I'm still seeing the same error:
```
Traceback (most recent call last):
  File "/scripts/bitwise.py", line 31, in <module>
    model_trt = torchtrt.compile(
  File "/usr/local/lib/python3.8/dist-packages/torch_tensorrt/_compile.py", line 115, in compile
    return torch_tensorrt.ts.compile(ts_mod, inputs=inputs, enabled_precisions=enabled_precisions, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch_tensorrt/ts/_compiler.py", line 113, in compile
    compiled_cpp_mod = _C.compile_graph(module._c, _parse_compile_spec(spec))
RuntimeError: [Error thrown at core/ir/ir.cpp:17] Expected vals.size() == specs.size() to be true but got false
Expected dimension specifications for all input tensors, but found 2 input tensors and 1 dimension specs
```
Should I reopen this issue or create a new one?

**Comment by chaoz-dev** [comment]
Fix is confirmed.
