### ISSUE TITLE
🐛 [Bug] Converting `torch.stack` with a negative dim argument results in error: `RuntimeError: [Error thrown at core/util/trt_util.cpp:165] pos >= 0 && pos <= d.nbDims ASSERT FAILED at core/util/trt_util.cpp:165, consider filing a bug: https://www.github.com/NVIDIA/Torch-TensorRT/issues ERROR: Index to unsqueeze is out of bounds.`

### ISSUE THREAD

**Issue by chaoz-dev** [NVIDIA/Torch-TensorRT#931]
##  Bug Description
Running `torch.stack` with a negative dimension as the stacking dimension results in the following error:
```
RuntimeError: [Error thrown at core/util/trt_util.cpp:165] pos >= 0 && pos <= d.nbDims ASSERT FAILED at core/util/trt_util.cpp:165, consider filing a bug: https://www.github.com/NVIDIA/Torch-TensorRT/issues
ERROR: Index to unsqueeze is out of bounds.
```
We should probably consider supporting this use case (ie. perform the negative to positive dimension conversion before applying TRT) as it's fairly common. 

## To Reproduce
```
  import torch    
  import torch_tensorrt as torchtrt    
  import torch_tensorrt.logging as logging    
      
  logging.set_reportable_log_level(logging.Level.Warning)    
      
  torch.manual_seed(0)    
      
  DEVICE = torch.device("cuda:0")    
  SHAPE = (1,)    
      
      
  class Model(torch.nn.Module):    
      def __init__(self):    
          super().__init__()    
      
      def forward(self, a):    
          return torch.stack((a, a), -1)    
      
      
  if __name__ == "__main__":    
      tensor = torch.randn(SHAPE, dtype=torch.float32, device=DEVICE)    
      
      model = Model().eval().to(DEVICE)    
      out = model(tensor)    
      print(f"Model: {out}")    
      
      model_trt = torchtrt.compile(    
          model,    
          inputs=[    
              torchtrt.Input(shape=SHAPE),    
          ],    
          enabled_precisions={torch.float},    
      )    
      out_trt = model(tensor)    
      print(f"Model TRT: {out_trt}")    
      
      assert torch.max(torch.abs(out - out_trt)) < 1e-6
```
Outputs the following:
```
root@5aff83435cc7:/workspace# python /scripts/stack.py
Model: tensor([[-0.9247, -0.9247]], device='cuda:0')
WARNING: [Torch-TensorRT] - Cannot infer input type from calcuations in graph for input a.1. Assuming it is Float32. If not, specify input type explicity
Traceback (most recent call last):
  File "/scripts/stack.py", line 30, in <module>
    model_trt = torchtrt.compile(
  File "/usr/local/lib/python3.8/dist-packages/torch_tensorrt/_compile.py", line 97, in compile
    return torch_tensorrt.ts.compile(ts_mod, inputs=inputs, enabled_precisions=enabled_precisions, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch_tensorrt/ts/_compiler.py", line 119, in compile
    compiled_cpp_mod = _C.compile_graph(module._c, _parse_compile_spec(spec))
RuntimeError: [Error thrown at core/util/trt_util.cpp:165] pos >= 0 && pos <= d.nbDims ASSERT FAILED at core/util/trt_util.cpp:165, consider filing a bug: https://www.github.com/NVIDIA/Torch-TensorRT/issues
ERROR: Index to unsqueeze is out of bounds.
```
    
## Expected behavior
Compilation should succeed and stack as in the non-TRT case:
```
Model: tensor([[-0.9247, -0.9247]], device='cuda:0')
```

## Environment
Ubuntu 18.04 x86-64
- Master (11bcb98d3cd680c3c34e6cc4c4efdc7512c144cc) using TRT NGC 22.02-py3
- v1.0 using TRT NGC 21.11-py3

Error appears in both.

## Additional context
This might be better considered a feature request.

**Comment by narendasan** [comment]
@inocsin Did you work on negative indexing for squeeze/unsqueeze?

**Comment by chaoz-dev** [comment]
Confirmed this fix.
