### ISSUE TITLE
🐛 [Bug] RuntimeError: [Error thrown at core/conversion/converters/impl/select.cpp:236] Expected const_layer to be true but got false

### ISSUE THREAD

**Issue by pupumao** [NVIDIA/Torch-TensorRT#945]
##  Bug Description

when i convert jit model, got the error
this is my forward code: 
input `x` shape is `(batch, 6, height, width)`, first step is to split `x` into two tensors, but failed
```
    def forward(self, x):
        fg = x[:,0:3,:,:]   ## this line got error
        bg = x[:,3:,:,:]
        
        fg = self.backbone(fg)
        bg = self.backbone(bg)
        out = self.heads(fg, bg)
        return out
```
complete traceback:
```
ERROR: [Torch-TensorRT TorchScript Conversion Context] - 3: [network.cpp::addConstant::1052] Error Code 3: Internal Error (Parameter check failed at: optimizer/api/network.cpp::addConstant::1052, condition: !weights.values == !weights.count
)
Traceback (most recent call last):
  File "model_converter.py", line 263, in <module>
    engine = get_engine(model_info.trt_engine_path, calib, int8_mode=int8_mode, optimize_params=optimize_params)
  File "model_converter.py", line 173, in get_engine
    return build_engine(max_batch_size)
  File "model_converter.py", line 95, in build_engine
    return build_engine_from_jit(max_batch_size)
  File "model_converter.py", line 80, in build_engine_from_jit
    tensorrt_engine_model = torch_tensorrt.ts.convert_method_to_trt_engine(traced_model, "forward", **compile_settings)
  File "/usr/local/lib/python3.6/dist-packages/torch_tensorrt/ts/_compiler.py", line 211, in convert_method_to_trt_engine
    return _C.convert_graph_to_trt_engine(module._c, method_name, _parse_compile_spec(compile_spec))
RuntimeError: [Error thrown at core/conversion/converters/impl/select.cpp:236] Expected const_layer to be true but got false
Unable to create constant layer from node: %575 : Tensor = aten::slice(%570, %13, %12, %14, %13) # /data/small_detection/centernet_pytorch_small_detection/models/low_freeze_comb_net.py:455:0
```

## Environment

> Build information about Torch-TensorRT can be found by turning on debug messages

 - PyTorch Version (e.g., 1.0): 1.4.0
 - CPU Architecture: arm (nx)
 - OS (e.g., Linux):
 - How you installed PyTorch: docker of nvidia l4t
 - Python version: 3.6.9
 - CUDA version: 10.2.300
 - Tensorrt version: 8.0.1.6

**Comment by p517332051** [comment]
I tried to reproduce your bug with your code, but it works.Maybe your torch version is too low，try to use higher than torch 1.8.0.

**Comment by pupumao** [comment]
> 

I use 1.10.0 but still got same error

I tested in embed arm device, not on gpu, may be difference ?

**Comment by narendasan** [comment]
Can you provide the code to reproduce this?

**Comment by inocsin** [comment]
> > 
> 
> I use 1.10.1 to trace jit model, but still got same error my steps: 1、trace jit model on training environment (GPU nvidia tesla T4, torch 1.10.1+cu102 (at first I use 1.4.0)) 2、use torch_tensorrt to convert jit model to tensorrt engine (nvidia xavier, torch 1.10.0)
> 
> I tested in embed arm device, not on gpu, may be difference ?

@pupumao This may due to dynamic shape issue, can you try this pr https://github.com/pytorch/TensorRT/pull/1110

**Comment by pupumao** [comment]
already solved

it's not a bug, just because wrong input setting for torch-tensorrt api(error kept require_grad=True)
