### ISSUE TITLE
❓ [Question] how to enable "torch fallback"

### ISSUE THREAD

**Issue by handoku** [NVIDIA/Torch-TensorRT#977]
## ❓ Question

I was told that torch-trt was able to partially convert graph to tensorrt while keep the unsupported part running on torch-runtime.
And I also hava Found some 'Torch Fallback' or 'torch_fallback' str at the source code.

So I generate a module containing `torch.argmax` , which is not supported by torch-tensorrt. And give it a shot, but it failed.

I hava two question:
1.  Is the fallback feature really supported by torch-tensorrt or is going to be supported?
2.  If allready supported, is there any sample showing how to use it.

## What you have already tried

take a look at this script:
```python
import torch
import torch_tensorrt
import numpy as np
from torchvision import models

class MyModel(torch.nn.Module):

    def __init__(self):
        super(MyModel, self).__init__()
        models_dict = {
            "resnet50_v2": models.resnet50,
            "resnet101_v2": models.resnet101,
            "resnet152_v2": models.resnet152,
            "mobilenet_v2": models.mobilenet_v2,
            "shufflenet_v2": models.shufflenet_v2_x1_0,
            "densenet169": models.densenet169
        }

        self.model = models_dict['resnet50_v2'](pretrained=False)

    def forward(self, x):
        x = self.model(x)
        return torch.argmax(x, -1)

def main():
    model = MyModel().eval().cuda()  #.cuda()
    x = torch.from_numpy(np.random.randn(1,3,224,224).astype(np.float32)).cuda()
    scripted_model = torch.jit.script(model)

    compile_settings = {
        "inputs": [x],
        "enabled_precisions": {torch.float},
        "torch_fallback":  { # also tryied with Torch Fallback
            "enabled": True
            "min_block_size": 1
            "forced_fallback_operators": [
            ]
            "forced_fallback_modules": [
            ]
        }
    }
    trt_ts_module = torch_tensorrt.ts.compile(scripted_model, **compile_settings)
    print(trt_ts_module)

    torch_tensorrt_out = trt_ts_module(x)
    print('torch_tensorrt_out shape: \n', torch_tensorrt_out.shape, print(torch_tensorrt_out))

    pytorch_out = model(x)
    print('pytorch out shape: \n', pytorch_out.shape, pytorch_out)

# torch._C._jit_to_backend is buggy, spec will be transformed into wrong json structure.
def main2():
    model = MyModel().eval().cuda()  #.cuda()
    x = torch.from_numpy(np.random.randn(1,3,224,224).astype(np.float32))
    scripted_model = torch.jit.script(model)

    spec = {
    "forward":
        torch_tensorrt.ts.TensorRTCompileSpec({
            "inputs": [torch_tensorrt.Input([1, 3, 224, 224], dtype=torch.float)],
            "enabled_precisions": {torch.float},
            "refit": False,
            "debug": False,
            "device": {
                "device_type": torch_tensorrt.DeviceType.GPU,
                "gpu_id": 0,
                "dla_core": 0,
                "allow_gpu_fallback": True
            },
            "capability": torch_tensorrt.EngineCapability.default,
            "num_min_timing_iters": 2,
            "num_avg_timing_iters": 1,
        })
    }

    trt_ts_module = torch._C._jit_to_backend("tensorrt", script_model, spec)
    print(trt_ts_module)

    torch_tensorrt_out = trt_ts_module(x)
    print('torch_tensorrt_out shape: \n', torch_tensorrt_out.shape, print(torch_tensorrt_out))

    pytorch_out = model(x)
    print('pytorch out shape: \n', pytorch_out.shape, pytorch_out)

if __name__ == "__main__":
    main()
```

get output:
```bash
Traceback (most recent call last):
  File "./torch_trt_custom.py", line 86, in <module>
    main()
  File "./torch_trt_custom.py", line 42, in main
    trt_ts_module = torch_tensorrt.ts.compile(scripted_model, **compile_settings)
TypeError: compile() got an unexpected keyword argument 'torch_fallback'
```
## Environment

ngc pytorch 22.02

**Comment by handoku** [comment]
closing this issue for having found some mistakes.
